ALTER TABLE articles DROP COLUMN IF EXISTS clinic_id;
ALTER TABLE categories DROP COLUMN IF EXISTS clinic_id;
ALTER TABLE animals DROP COLUMN IF EXISTS clinic_id;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS clinics;
